// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCgsNYX5GRMAMa8LBiy92oGNRO_Uq9jobo',
    appId: '1:878491558628:web:29b656a1eaccb2dcdf82f1',
    messagingSenderId: '878491558628',
    projectId: 'expensetracker-48377',
    authDomain: 'expensetracker-48377.firebaseapp.com',
    storageBucket: 'expensetracker-48377.appspot.com',
    measurementId: 'G-B7QK0CRKHD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDKtHZQM2rppLVffFy7TeGKiwNc_Qfukwk',
    appId: '1:878491558628:android:36e67eeb1be2dc80df82f1',
    messagingSenderId: '878491558628',
    projectId: 'expensetracker-48377',
    storageBucket: 'expensetracker-48377.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCXE6UCFUK-mDylyb1W1iZI0DNG4kA6uMA',
    appId: '1:878491558628:ios:e96feecf4c958dd6df82f1',
    messagingSenderId: '878491558628',
    projectId: 'expensetracker-48377',
    storageBucket: 'expensetracker-48377.appspot.com',
    iosBundleId: 'com.example.expensetracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCXE6UCFUK-mDylyb1W1iZI0DNG4kA6uMA',
    appId: '1:878491558628:ios:6d9eeaec4ca60748df82f1',
    messagingSenderId: '878491558628',
    projectId: 'expensetracker-48377',
    storageBucket: 'expensetracker-48377.appspot.com',
    iosBundleId: 'com.example.expensetracker.RunnerTests',
  );
}
